backend:
  name: github
  repo: Metainy/resume
media_folder: "src/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - name: "resume"
    label: "Resume"
    file: "src/docs/index.md"
    delete: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
